'use strict';

AG.GLOSSARY = [
  { term: 'Atomic', ch: 'race', def: 'Can’t be seen half-done: to everyone else, it either hasn’t happened or has completely happened. In JavaScript, any code with no <code>await</code> in it is atomic with respect to other async code.' },
  { term: 'Await', ch: 'promises', def: 'Pauses the current async function until a promise settles. The brain is free for other code in the meantime. Every <code>await</code> ends a turn, so shared state may have changed by the time the function resumes.' },
  { term: 'BFS (breadth-first search)', ch: 'mission', def: 'Exploring a graph level by level with a first-in-first-out queue and a seen-set. The single-threaded crawler.' },
  { term: 'Busy-waiting (polling)', ch: 'nursery', def: 'Waiting for something by checking it over and over. Wastes work and adds delay. Without an <code>await</code> inside the loop, in JavaScript it freezes everything.' },
  { term: 'Callback', ch: 'event-loop', def: 'A function handed over to be called later, when some wait is over.' },
  { term: 'Check-then-act', ch: 'race', def: 'A race where a worker checks a condition, and then acts on it after a gap in which another worker can change it. Fixed by making the check and the act one atomic step.' },
  { term: 'Concurrency', ch: 'waiting', def: 'Several jobs in progress at the same time, with overlapping lifetimes, even if only one is actively running at any instant.' },
  { term: 'Condition variable', ch: 'nursery', def: 'A place where workers sleep until a condition might have become true, with operations to wake one (<code>notify</code>) or all (<code>notifyAll</code>). With threads, always used together with a lock. In the game: the nursery.' },
  { term: 'Critical section', ch: 'mutex', def: 'A stretch of code that must not be interleaved with other workers running the same stretch.' },
  { term: 'Deadlock', ch: 'mutex', def: 'Workers waiting forever for something that will never happen, such as a key nobody will return. Nothing crashes; everything just stops.' },
  { term: 'Event loop', ch: 'event-loop', def: 'The part of JavaScript that picks what runs next: one task, then all microtasks, then the next task, forever.' },
  { term: 'GIL', ch: 'threads', def: 'CPython’s Global Interpreter Lock. Only one thread runs Python code at a time, but threads can still be switched between almost any two steps.' },
  { term: 'Lost update', ch: 'mutex', def: 'Two read-modify-write sequences overlap, and one overwrites the other’s result.' },
  { term: 'Lost wake-up', ch: 'nursery', def: 'A wake-up signal sent between a worker checking the condition and falling asleep, so it is missed. Prevented in JavaScript by doing both in one turn, and with threads by holding the lock.' },
  { term: 'Microtask', ch: 'event-loop', def: 'A follow-up job, such as the continuation after an await or a <code>.then</code> callback. All microtasks run before the next task.' },
  { term: 'Mutex (lock)', ch: 'mutex', def: 'Mutual exclusion: only the holder of the lock may run the protected code. In the game: the storeroom key.' },
  { term: 'Parallelism', ch: 'waiting', def: 'Several things happening at the exact same instant, on several brains (threads or CPU cores).' },
  { term: 'Promise', ch: 'promises', def: 'An object standing for a result that isn’t ready yet: pending, then fulfilled with a value or rejected with an error. In the game: an order slip.' },
  { term: 'Promise.all', ch: 'promises', def: 'Turns an array of promises into one promise of an array of results, in the original order. Rejects if any of them rejects.' },
  { term: 'Race condition', ch: 'race', def: 'A bug where the outcome depends on the timing or ordering of concurrent workers.' },
  { term: 'Read-modify-write', ch: 'mutex', def: 'Read a shared value, compute a new one from it, write it back. Unsafe if anything can happen between the read and the write.' },
  { term: 'Resolve', ch: 'promises', def: 'The function that fulfils a promise made with <code>new Promise</code>. Keeping it for later is how mutexes and condition variables are built in JavaScript.' },
  { term: 'Seen-set', ch: 'mission', def: 'The set of every page ever queued, used to avoid doing the same page twice. Mark pages when they are discovered, not when they are visited.' },
  { term: 'Spurious wake-up', ch: 'threads', def: 'A thread returning from <code>wait()</code> without having been notified. Harmless if you always wait in a <code>while</code> loop.' },
  { term: 'Task', ch: 'event-loop', def: 'A callback whose wait is over (a timer, a network response, a click), queued for the event loop to run.' },
  { term: 'Termination detection', ch: 'pool', def: 'Knowing when concurrent work is really finished: nothing waiting in the queue and nothing in progress.' },
  { term: 'Thread', ch: 'waiting', def: 'An independent line of execution: a brain. JavaScript gives your code one; most other languages let you have many.' },
  { term: 'Thundering herd', ch: 'nursery', def: 'Waking every sleeping worker when only one can have the new job; the rest wake for nothing.' },
  { term: 'Turn', ch: 'event-loop', def: 'The game’s word for one uninterrupted run of JavaScript, from its start (or an await resuming) to its end (or the next await). Officially: run-to-completion.' },
  { term: 'Worker pool', ch: 'pool', def: 'A fixed number of workers sharing a queue of jobs, each looping: take a job, do it, repeat.' },
];
